### PR TITLE
Add functional variant of threefry

### PR DESCRIPTION
**Pull request by jw3126**
In some contexts, mutable structs are problematic (for instance on GPU). This adds a low-level purely functional way to use threefry.
If there is interest in this, I will add functional variants of the other rngs as well. 
I can also add a convenience function for functional counter increment if desired.

### CODE REVIEW

**Comment by jw3126** [comment]
@sunoru any thoughts on having a side effect-free low-level API?

**Comment by sunoru** [comment]
Sorry for replying late! Having such low-level APIs sounds useful. Can you also help add them to other RNGs?

**Comment by jw3126** [comment]
@sunoru I added the other rngs. Currently `aesni` and `ars` operate on `__m128i` which I am not sure we want to expose? Should I sandwich `aesni` and `ars` in conversion functions that let them operate on `UInt128` instead?

**Comment by sunoru** [comment]
Sure I guess we can just also have a version of `aesni` and `ars` to operate on `UInt128` values.

**Comment by jw3126** [comment]
I added such `aesni` and `ars` could you run CI?

**Comment by sunoru** [comment]
OK! BTW, I think it's OK to export these functions.

**Comment by sunoru** [comment]
Looks good to me. Thanks very much!

**Pull request merged**
